spring.datasource.url=jdbc:postgresql://prod-server:5432/legal_system
spring.datasource.username=postgres
spring.datasource.password=Adhi@2004

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true