# Local DB (your laptop)
spring.datasource.url=jdbc:postgresql://localhost:5432/legal_system
spring.datasource.username=legal_user
spring.datasource.password=legal@321

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true